---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: gitops-infra
  namespace: openshift-gitops
stringData:
  type: git
  url: https://github.com/mstefany/gitops-infra
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: github-credentials
  namespace: openshift-gitops
stringData:
  password: ""
  type: git
  url: https://github.com/mstefany
  username: mstefany
